//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCADABepTuDongWPFV3.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class StepRecipe
    {
        public int Id { get; set; }
        public int IdRecipe { get; set; }
        public Nullable<int> NumberStep { get; set; }
        public string DisplayName { get; set; }
        public string C_Param { get; set; }
        public Nullable<int> C_Temp { get; set; }
        public Nullable<int> C_Hours { get; set; }
        public Nullable<int> C_Minutes { get; set; }
        public Nullable<int> C_Seconds { get; set; }
    
        public virtual Recipe Recipe { get; set; }
    }
}
