//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCADABepTuDongWPFV3.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CookerAddress
    {
        public int ID { get; set; }
        public string CookerName { get; set; }
        public string CookerAddress1 { get; set; }
    }
}
