//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCADABepTuDongWPFV3.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ingredient
    {
        public int sTT { get; set; }
        public int Id { get; set; }
        public string DisplayName { get; set; }
        public string Unit { get; set; }
    }
}
