//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCADABepTuDongWPFV3.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SCADABepTuDongV3Entities : DbContext
    {
        public SCADABepTuDongV3Entities()
            : base("name=SCADABepTuDongV3Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CookerAddress> CookerAddresses { get; set; }
        public virtual DbSet<Ingredient> Ingredients { get; set; }
        public virtual DbSet<IngredientUnit> IngredientUnits { get; set; }
        public virtual DbSet<Recipe> Recipes { get; set; }
        public virtual DbSet<RobotActionCode> RobotActionCodes { get; set; }
        public virtual DbSet<StepRecipe> StepRecipes { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
